### ISSUE TITLE
การแชร์รูป

### ISSUE THREAD

**Issue by forunh** [oat9002/Move-Move-Alarm#3]
หลังถ่ายรูป ถ้ากดแชร์ ให้แชร์รูปที่ถ่ายพร้อมกับรูปท่าที่ออกกำลัง พร้อมแคปชั่นที่ชวนให้มาโหลดแอพ

**Comment by monthonint** [comment]
รวมรูปได้ละ ส่วนแคปชั่นยังไม่ได้ทำ แล้วก็เหมือนจะมีปัญหาที่ตัวdialogที่เตือนว่าอัพรูปเสร็จแล้วหรือยัง ไม่รู้ว่าทำไมเลยทำเป็น comment ไว้ก่อน

**Comment by monthonint** [comment]
เพิ่ม caption ได้แล้ว แต่ต้องไปใส่ส่วนของ txt รับค่าจากผู้ใช้ก่อน

**Comment by forunh** [comment]
เหลือแก้ขนาดรูปให้เหมาะสม
