### ISSUE TITLE
หน้าตั้งค่า

### ISSUE THREAD

**Issue by forunh** [oat9002/Move-Move-Alarm#9]
เอาหน้าตั้งค่าออก เอาออกจากเมนูด้วย
ย้ายการตั้งค่าในหน้าตั้งค่าไปรวมกับหน้าตั้งค่าการเตือน

**Comment by forunh** [comment]
@monthonrose  เรามีแก้หน้าตั้งค่าการเตือนไว้ ตอนนี้mergeลงdeveloperแล้ว แก้ต่อได้เลยนะ

**Comment by monthonint** [comment]
แก้ไขหน้า Fragment_alarm กับ ลบ หน้าการตั้งค่า
